### ISSUE TITLE
Error when shutting down server (/ stop)

### ISSUE THREAD

**Issue by tncc2k** [OmerBenGera/WildStacker#20]
Spigot build: 1.10.2
WildStacker: 3.5.1

Error code:

[22:29:49 ERROR]: Error occurred while disabling WildStacker v3.5.1 (Is it up to date?)
java.lang.IllegalStateException: no implementation set
        at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:65) ~[?:?]
        at net.citizensnpcs.api.CitizensAPI.getNPCRegistry(CitizensAPI.java:96) ~[?:?]
        at com.bgsoftware.wildstacker.hooks.CitizensHook.isNPC(CitizensHook.java:9) ~[?:?]
        at com.bgsoftware.wildstacker.utils.entity.EntityUtils.isStackable(EntityUtils.java:143) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.handleChunkUnload(SystemHandler.java:591) ~[?:?]
        at com.bgsoftware.wildstacker.WildStackerPlugin.onDisable(WildStackerPlugin.java:158) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:294) ~[skyblock1102.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [skyblock1102.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [skyblock1102.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [skyblock1102.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.disablePlugins(CraftServer.java:342) [skyblock1102.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.stop(MinecraftServer.java:455) [skyblock1102.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:603) [skyblock1102.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by OmerBenGera** [comment]
This is something with Citizens, contact them to find out why it occurs.
