### ISSUE TITLE
Issue with FabledSkyblock API

### ISSUE THREAD

**Issue by DoctaEnkoda** [OmerBenGera/WildStacker#21]
`[FabledSkyBlock] Task #1836672 for FabledSkyBlock v2.3.23b generated an exception
java.lang.ClassCastException: class com.songoda.skyblock.levelling.QueuedIslandScan cannot be cast to class com.songoda.skyblock.levelling.IslandScan (com.songoda.skyblock.levelling.QueuedIslandScan and com.songoda.skyblock.levelling.IslandScan are in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @6baac14a)
        at com.bgsoftware.wildstacker.hooks.PluginHook_FabledSkyblock.getAmount(PluginHook_FabledSkyblock.java:57) ~[?:?]
        at com.songoda.skyblock.levelling.IslandLevelManager.getAmountAndType(IslandLevelManager.java:215) ~[?:?]
        at com.songoda.skyblock.levelling.IslandScan.run(IslandScan.java:101) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1377) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:356) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1290) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1017) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at java.lang.Thread.run(Thread.java:832) [?:?]`
        
Hard spam actualy

**Comment by OmerBenGera** [comment]
What version of FabledSkyblock are you using?

**Comment by DoctaEnkoda** [comment]
https://github.com/songoda/FabledSKyblock

**Comment by OmerBenGera** [comment]
Tag me on the discord server, I'll need a copy of the jar so I can add support for it

**Comment by OmerBenGera** [comment]
Build #42 will fix it :)
