### ISSUE TITLE
Issue Event SlimeSplitEvent 

### ISSUE THREAD

**Issue by DoctaEnkoda** [OmerBenGera/WildStacker#22]
`[03:06:09 WARN]: [WildStacker] Plugin WildStacker v3.5.1 generated an exception while executing task 36771
java.lang.IllegalStateException: SlimeSplitEvent may only be triggered synchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:599) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at net.minecraft.server.v1_16_R3.EntitySlime.die(EntitySlime.java:182) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.remove(CraftEntity.java:486) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at com.bgsoftware.wildstacker.objects.WStackedEntity.remove(WStackedEntity.java:195) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.lambda$null$32(SystemHandler.java:762) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.lambda$performKillAll$35(SystemHandler.java:758) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-SinonMC-333b276]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]`

**Comment by OmerBenGera** [comment]
I will check it out, thanks for reporting!

**Comment by OmerBenGera** [comment]
Fixed in build #37 :)
