### ISSUE TITLE
ClassCastException - Citizens and WildStacker

### ISSUE THREAD

**Issue by Skizzles** [OmerBenGera/WildStacker#62]
[02:40:13] [Server thread/ERROR]: Could not pass event EntityRemoveFromWorldEvent to WildStacker v3.5.1
java.lang.ClassCastException: class net.minecraft.server.v1_16_R3.EntityVillager cannot be cast to class net.citizensnpcs.npc.ai.NPCHolder (net.minecraft.server.v1_16_R3.EntityVillager is in unnamed module of loader 'app'; net.citizensnpcs.npc.ai.NPCHolder is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @357a84ef)
	at net.citizensnpcs.nms.v1_16_R3.util.ForwardingNPCHolder.getNPC(ForwardingNPCHolder.java:11) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.getNPC(CitizensNPCRegistry.java:162) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPCRegistry.isNPC(CitizensNPCRegistry.java:168) ~[?:?]
	at com.bgsoftware.wildstacker.hooks.CitizensHook.isNPC(CitizensHook.java:18) ~[?:?]
	at com.bgsoftware.wildstacker.utils.entity.EntityUtils.isStackable(EntityUtils.java:154) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityRemove(EntitiesListener.java:911) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.PaperListener.onEntityRemove(PaperListener.java:13) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1736.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-967]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-967]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-967]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-967]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[patched_1.16.5.jar:git-Purpur-967]
	at net.minecraft.server.v1_16_R3.WorldServer.unregisterEntity(WorldServer.java:1861) ~[patched_1.16.5.jar:git-Purpur-967]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:918) ~[patched_1.16.5.jar:git-Purpur-967]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1435) ~[patched_1.16.5.jar:git-Purpur-967]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-967]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1284) ~[patched_1.16.5.jar:git-Purpur-967]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1010) ~[patched_1.16.5.jar:git-Purpur-967]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[patched_1.16.5.jar:git-Purpur-967]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by OmerBenGera** [comment]
Did it happened when you deleted an NPC of Citizens with a Villager type?

**Comment by OmerBenGera** [comment]
I can't seem to replicate the issue - also it looks like an issue on Citizens' side, as it happens after WildStacker calls net.citizensnpcs.npc.CitizensNPCRegistry#isNPC

**Comment by Skizzles** [comment]
Seems to have happened after moving a Villager NPC to a new world using citizens.

**Comment by OmerBenGera** [comment]
I can't seem to replicate the error

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by Skizzles** [comment]
Have not been able to replicate further, possibly fixed after updating.

**Comment by OmerBenGera** [comment]
I will close this issue for now.
If it happens again, simply reopen it
