### ISSUE TITLE
Mob stack comes back after stacker kill

### ISSUE THREAD

**Issue by MythricHD** [OmerBenGera/WildStacker#84]
Tested on b89

So whenever I have a mob stack (doesn't matter if it's updated or not), if a player is hitting the stack of mobs and a stacker kill occurs then there is a chance the stack will spawn back, and if its an upgraded mob type then it spawns the default tier. 

I can get images/config if this would help if you are not able to reproduce.

**Comment by OmerBenGera** [comment]
Take a video of the issue please.

**Comment by MythricHD** [comment]
https://i.riftmc.co/J3WFvP2l6F.gif

Config if needed: 
[archive-2021-03-19T055207-0400.tar.gz](https://github.com/OmerBenGera/WildStacker/files/6170179/archive-2021-03-19T055207-0400.tar.gz)

**Comment by OmerBenGera** [comment]
Try it on Paper with only WildStacker installed - it doesn't look like an issue with the plugin for me

**Comment by MythricHD** [comment]
Did some more testing on vanilla server with default config and it still happened: https://i.riftmc.co/ApCxVX28HY.gif 
I changes there config options to make it quicker to reprocude, its possible one of these options may be causing it:
next-stack-knockback: false
spawn-corpses: false
one-shot:
  enabled: true

**Comment by OmerBenGera** [comment]
> 
> 
> Did some more testing on a vanilla server with default config and it still happened: https://i.riftmc.co/ApCxVX28HY.gif
> I changed these config options to make it quicker to reproduce, its possible one of these options may be causing it:
> next-stack-knockback: false
> spawn-corpses: false
> one-shot:
> enabled: true

Check out latest dev build, let me know if it fixes the issue

**Comment by MythricHD** [comment]
Persists on b94. Looks like after it happens the mob is no longer nerfed: https://i.riftmc.co/M5gP4UKYsH.gif

**Comment by OmerBenGera** [comment]
The mob repeared with half of its stack size, why?

**Comment by MythricHD** [comment]
No clue it's all very odd but maybe because of the potential fix? Didn't think that happened before

**Comment by MythricHD** [comment]
Just an update: Issue Still persists on the version pushed to spigot (v3.5.2)

**Comment by TouchBrown** [comment]
I did some testing with this and the cause is if someone kills the mob when the clear lag happens and you have spawn-corpses set to false.  It's weird because the stack actually disappears then reappears though

**Comment by TouchBrown** [comment]
So I'm not 100% knowledgeable about this, but is this on a 2 tick delay or something?  Could this be respawning the mob after dying?  https://github.com/BG-Software-LLC/WildStacker/blob/132ad074d355cfaeacfb7c3a1264a661ae76989d/src/main/java/com/bgsoftware/wildstacker/objects/WStackedEntity.java#L424-L429

**Comment by OmerBenGera** [comment]
> 
> 
> So I'm not 100% knowledgeable about this, but is this on a 2 tick delay or something? Could this be respawning the mob after clearing it if you killed it 1 tick before?
> 
> https://github.com/BG-Software-LLC/WildStacker/blob/132ad074d355cfaeacfb7c3a1264a661ae76989d/src/main/java/com/bgsoftware/wildstacker/objects/WStackedEntity.java#L424-L429

This delay kills the corpses tho, not spawning them again. Maybe @MythricHD you have something that prevents them from dying? Try disabling spawn-corpse and let me know if it helps

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by MythricHD** [comment]
We tried disabling spawn corpse and it happened or a rare chance because we cant hit the mobs as fast

**Comment by MythricHD** [comment]
@TouchBrown Can you confirm this?

**Comment by TouchBrown** [comment]
> We tried disabling spawn corpse and it happened or a rare chance because we cant hit the mobs as fast

this sums it up we have to kill it pretty much tick of the kill all so it would be very hard to test with spawn corpse as the corpses get in the way

**Comment by TouchBrown** [comment]
Any chance that it has something to do with this being done as the killall happens? https://github.com/BG-Software-LLC/WildStacker/blob/132ad074d355cfaeacfb7c3a1264a661ae76989d/src/main/java/com/bgsoftware/wildstacker/objects/WStackedEntity.java#L698

**Comment by OmerBenGera** [comment]
@MythricHD Were you able to replicate it on a private server with only you being online?
I want to add debug stack-trace to spawned entities, but it's not gonna work if we do that on a server where entities are constantly spawned to the world

**Comment by MythricHD** [comment]
I have tried on a private server with my and my alt. Its hard to replicate solo since you need to hit the mobs also while clearing the entities. I could try to do it solo but do you think it's going to make a difference?

**Comment by OmerBenGera** [comment]
> 
> 
> I have tried on a private server with my and my alt. Its hard to replicate solo since you need to hit the mobs also while clearing the entities. I could try to do it solo but do you think it's going to make a difference?

Yes, as if you manage to do so, I can add debug stack trace and we should find out how they spawn (in other words, what function makes them to spawn). I can't do it on a server with a lot of players, as it's just gonna flood your console with these stack traces and we will not be able to find the cause

**Comment by MythricHD** [comment]
Yeah, I can do that.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by TouchBrown** [comment]
Does one of the builds have this debug option?

**Comment by OmerBenGera** [comment]
> Does one of the builds have this debug option?

No... dev builds will never have debug messages.

**Comment by MythricHD** [comment]
We were under the impression that you were giving us a build with the debug output. If that wasn't the case,  what did you want us to test?

**Comment by OmerBenGera** [comment]
> We were under the impression that you were giving us a build with the debug output. If that wasn't the case, what did you want us to test?

You should first try it on another server where only you play, so the debug message will be effective.

**Comment by TouchBrown** [comment]
Yes we can do that if you send us a build with the debug message.

**Comment by OmerBenGera** [comment]
Were you able to achieve this on a standalone server tho? I know you can try it, but were you even able to replicate the issue?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by MythricHD** [comment]
If you were asking if I was able to replicate it on a standalone server then yes that is what I did before reporting the issue

**Comment by MythricHD** [comment]
`[11:02:46 INFO]: Entity ZOMBIE spawned:
[11:02:46 WARN]: java.lang.Exception
[11:02:46 WARN]:        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntitySpawn(EntitiesListener.java:534)
[11:02:46 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor333.execute(Unknown Source)
[11:02:46 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(:70)
[11:02:46 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(:74)
[11:02:46 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(:62)
[11:02:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(:513)
[11:02:46 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callCreatureSpawnEvent(:286)
[11:02:46 WARN]:        at net.minecraft.server.v1_12_R1.World.addEntity(:1189)
[11:02:46 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.addEntity(:1138)
[11:02:46 WARN]:        at com.bgsoftware.wildstacker.nms.NMSSpawners_v1_12_R1$StackedMobSpawner.addEntity(NMSSpawners_v1_12_R1.java:548)
[11:02:46 WARN]:        at com.bgsoftware.wildstacker.nms.NMSSpawners_v1_12_R1$StackedMobSpawner.handleEntitySpawn(NMSSpawners_v1_12_R1.java:527)
[11:02:46 WARN]:        at com.bgsoftware.wildstacker.nms.NMSSpawners_v1_12_R1$StackedMobSpawner.c(NMSSpawners_v1_12_R1.java:454)
[11:02:46 WARN]:        at net.minecraft.server.v1_12_R1.TileEntityMobSpawner.e(:91)
[11:02:46 WARN]:        at net.minecraft.server.v1_12_R1.World.tickEntities(:1714)
[11:02:46 WARN]:        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(:675)
[11:02:46 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(:952)
[11:02:46 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(:429)
[11:02:46 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(:783)
[11:02:46 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(:674)
[11:02:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)`

Posted per discord ticket request. This is what was sent in console after a mob would respawn

**Comment by OmerBenGera** [comment]
This mob was spawned by a spawner, weird. Do you have spawners nearby by any chance?

**Comment by TouchBrown** [comment]
> This mob was spawned by a spawner, weird. Do you have spawners nearby by any chance?

When I did the test with mythric I broke the spawner so there was no nearby spawner

**Comment by OmerBenGera** [comment]
> 
> 
> > This mob was spawned by a spawner, weird. Do you have spawners nearby by any chance?
> 
> When I did the test with mythric I broke the spawner so there was no nearby spawner

Weird. The stack trace shows that the mob was spawned from spawner.
Does it happen all the time that it shows it comes out of a spawner?
If that's the case, try disabling spawners-override in the config and check if it temporary fixes the issue.

**Comment by TouchBrown** [comment]
Yeah whenever we stacker kill at the same time as hitting the mob that comes up regardless of there being a spawner nearby.  I'll have to check that config option though.

**Comment by OmerBenGera** [comment]
> 
> 
> Yeah whenever we stacker kill at the same time as hitting the mob that comes up regardless of there being a spawner nearby. I'll have to check that config option though.

then maybe that's not the stack trace of the bugged mob? The stack trace clearly shows that the mob was spawned by a spawner.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by MythricHD** [comment]
This is the exact stack trace of a bugged zombie stack from when it was spawned (first readout) and after I /stacker killed and the stack came back (second trace) https://paste.helpch.at/wudacedepo.md

**Comment by OmerBenGera** [comment]
What server jar are you using? Seems like a custom one, am I right?

**Comment by MythricHD** [comment]
Yes we use GuardSpigot, a 1.12.2 paper fork

**Comment by OmerBenGera** [comment]
Great, switch to paper and check if it works.
I think the Entity's remove method, for an unknown reason, calls the EntityDeathEvent and causes the plugin to get confused.

**Comment by MythricHD** [comment]
https://paste.helpch.at/jorosijavi.md Seems like the issue persists on 1.12.2 Paperspigot
