### ISSUE TITLE
ConcurrentModificationException when a player joins

### ISSUE THREAD

**Issue by ArtelGG** [OmerBenGera/WildStacker#9]
This exception occurred (it printed three separate times with different task numbers but the same exception) when a player joined the server shortly after it finished rebooting. All configuration settings are default. The server software is PaperSpigot 1.16.4 (389)

```
[07:26:24 WARN]: [WildStacker] Plugin WildStacker v3.5.0 generated an exception while executing task 6683
java.util.ConcurrentModificationException: null
        at java.util.HashMap.computeIfAbsent(HashMap.java:1134) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.persistence.CraftPersistentDataTypeRegistry.isInstanceOf(CraftPersistentDataTypeRegistry.java:228) ~[patched_1.16.4.jar:git-Paper-389]
        at org.bukkit.craftbukkit.v1_16_R3.persistence.CraftPersistentDataContainer.has(CraftPersistentDataContainer.java:53) ~[patched_1.16.4.jar:git-Paper-389]
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_16_R3.loadEntity(NMSAdapter_v1_16_R3.java:781) ~[?:?]
        at com.bgsoftware.wildstacker.hooks.DataSerializer_Default.loadEntity(DataSerializer_Default.java:22) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedEntity(SystemHandler.java:172) ~[?:?]
        at com.bgsoftware.wildstacker.objects.WStackedEntity.of(WStackedEntity.java:739) ~[?:?]
        at com.bgsoftware.wildstacker.objects.WStackedEntity.of(WStackedEntity.java:732) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.lambda$null$16(SystemHandler.java:547) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.lambda$handleChunkLoad$17(SystemHandler.java:546) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-389]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-389]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-389]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by OmerBenGera** [comment]
Build #17 should fix the issue
If it doesn't, let me know by opening the issue again :)
