### ISSUE TITLE
WorldGurd Hook

### ISSUE THREAD

**Issue by MZhenkM** [OmerBenGera/WildStacker#96]
Good evening, sorry for the inconvenience, I would like to report a bug with the latest development version that has been passed, I submitted a report and it was not given importance.

Starting with dev version "WildStacker-b90", this error appears when doing any kind of interaction with the stacker.

I tried each of the development versions and it works fine from b89 downwards, from b90 upwards it is broken.

This problem only occurs or at least to me in 1.12.2

I tested it on my current server with my server plugins and the problem continues, I decided to open a separate server, only with worldguard and stacker and the problem continues.

Try downloading it again and check the worldguard version to make sure there is no way to fix it.

Good evening, sorry for the inconvenience.

`[23:53:50 ERROR]: Could not pass event SpawnerStackEvent to WildStacker v3.5.1-DEVb97
java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
        at com.bgsoftware.wildstacker.hooks.WorldGuardHook$WorldGuardProvider.hasClaimAccess(WorldGuardHook.java:41) ~[?:?]
        at com.bgsoftware.wildstacker.hooks.WorldGuardHook.hasClaimAccess(WorldGuardHook.java:26) ~[?:?]
        at com.bgsoftware.wildstacker.hooks.ClaimsProvider_WorldGuard.hasClaimAccess(ClaimsProvider_WorldGuard.java:10) ~[?:?]
        at com.bgsoftware.wildstacker.handlers.ProvidersHandler.hasClaimAccess(ProvidersHandler.java:251) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.NoClaimConflictListener.onSpawnerStack(NoClaimConflictListener.java:51) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor925.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at com.bgsoftware.wildstacker.utils.events.EventsCaller.callSpawnerStackEvent(EventsCaller.java:110) ~[?:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.runStack(WStackedSpawner.java:247) ~[?:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.runStack(WStackedSpawner.java:226) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockPlace(SpawnersListener.java:173) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor931.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:151) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:230) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:513) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:993) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.WorldGuard
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[spigot.jar:git-TacoSpigot-"f8ba67d6"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 36 more`

**Comment by OmerBenGera** [comment]
What version of WorldGuard are you using?

**Comment by MZhenkM** [comment]
6.2.2, is the version that worldguard asks to use for 1.12.2

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
